check notebooks
asdf-format/tutorials pull request #17
Opened 2022-07-21 17:54 UTC by zacharyburnett

2022-07-22 14:12 UTC, zacharyburnett commented
```shell
python -m nbcollection execute .
```
```
[nbcollection (INFO)]: Collected 7 notebook files
[7](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:8)
[nbcollection (INFO)]: Finished running notebook 'Anatomy_of_an_ASDF_file.ipynb' (8.13 seconds) ✅
[8](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:9)
[nbcollection (INFO)]: Finished running notebook 'Validation_and_Dealing_with_Errors.ipynb' (1.10 seconds) ✅
[9](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:10)
[nbcollection (ERROR)]: Notebook 'Your_second_ASDF_converter.ipynb' errored ❌
[10](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:11)
[nbcollection (ERROR)]: Notebook 'Your_first_ASDF_converter.ipynb' errored ❌
[11](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:12)
[nbcollection (INFO)]: Finished running notebook 'Reading_a_JWST_ASDF_file.ipynb' (119.88 seconds) ✅
[12](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:13)
[nbcollection (INFO)]: Finished running notebook 'High_Level_Introduction_to_ASDF.ipynb' (1.17 seconds) ✅
[13](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:14)
[nbcollection (INFO)]: Finished running notebook 'ASDF_and_World_Coordinate_Systems.ipynb' (5.97 seconds) ✅
[14](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:15)
[nbcollection (ERROR)]: Notebook 'Your_second_ASDF_converter.ipynb' errored: An error occurred while executing the following cell:
[15](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:16)
------------------
[16](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:17)
import numpy as np
[17](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:18)
import asdf
[18](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:19)
from myconverters.photo_id import PhotoID
[19](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:20)
from myconverters.traffic_citation import TrafficCitation
[20](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:21)
------------------
[21](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:22)
[22](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:23)
---------------------------------------------------------------------------
[23](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:24)
ModuleNotFoundError                       Traceback (most recent call last)
[24](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:25)
Input In [38], in <cell line: 3>()
[25](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:26)
      1importnumpyasnp
[26](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:27)
      2importasdf
[27](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:28)
----> 3frommyconverters.photo_idimport PhotoID
[28](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:29)
      4frommyconverters.traffic_citationimport TrafficCitation
[29](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:30)
[30](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:31)
ModuleNotFoundError: No module named 'myconverters'
[31](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:32)
ModuleNotFoundError: No module named 'myconverters'
[32](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:33)
[33](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:34)
[nbcollection (ERROR)]: Notebook 'Your_first_ASDF_converter.ipynb' errored: An error occurred while executing the following cell:
[34](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:35)
------------------
[35](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:36)
import asdf
[36](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:37)
import numpy as np
[37](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:38)
import mfconverter.photo_id as pid
[38](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:39)
image = np.zeros((10,10), dtype=np.byte)
[39](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:40)
p = pid.PhotoID('man', 'invisible', image)
[40](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:41)
af = asdf.AsdfFile()
[41](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:42)
af.tree = {'id': p}
[42](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:43)
af.write_to('test1.asdf', auto_inline=200)
[43](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:44)
------------------
[44](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:45)
[45](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:46)
---------------------------------------------------------------------------
[46](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:47)
ModuleNotFoundError                       Traceback (most recent call last)
[47](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:48)
Input In [18], in <cell line: 3>()
[48](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:49)
      1importasdf
[49](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:50)
      2importnumpyasnp
[50](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:51)
----> 3importmfconverter.photo_idaspid
[51](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:52)
      4 image = np.zeros((10,10), dtype=np.byte)
[52](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:53)
      5 p = pid.PhotoID('man', 'invisible', image)
[53](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:54)
[54](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:55)
ModuleNotFoundError: No module named 'mfconverter'
[55](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:56)
ModuleNotFoundError: No module named 'mfconverter'
[56](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:57)
[57](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:58)
Traceback (most recent call last):
[58](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:59)
  File "/usr/share/miniconda/envs/asdf-tutorial-Linux-py3.10-latest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[59](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:60)
    return _run_code(code, main_globals, None,
[60](https://github.com/zacharyburnett/tutorials/runs/7456202660?check_suite_focus=true#step:8:61)
  File "/usr/share/miniconda/envs/asdf-tutorial-Linux-py3.10 [...]

2022-07-22 14:13 UTC, WilliamJamieson commented
The CI doesn't appear to be running on github.

2022-07-22 14:15 UTC, zacharyburnett commented
> The CI doesn't appear to be running on github.

yes, it's running in the fork but it seems not be running in this repository (perhaps because it's not in the main branch). I'm not sure why that is, but for this PR at least we can see the runs in the fork

2022-08-23 18:28 UTC, WilliamJamieson commented
Trying close/reopen

2022-10-05 13:50 UTC, WilliamJamieson commented
Could you add a simple `.pre-commit-config.yaml` file to this? We can try merging and seeing if we can run the CI then.

2022-10-05 13:52 UTC, WilliamJamieson requested changes

2022-10-05 18:22 UTC, braingram commented
Am I reading this right that the CI job to check notebooks is not yet running in the main branch?

Also, there are errors in the 2 notebooks: Your_first_ASDF_converter.ipynb and Your_second_ASDF_converter.ipynb

Both of these notebooks have cells that write files to disk (in a folder created in the home directory). Is this sort of pattern supported by nbcollection?

So far I've been unable to replicate those errors locally and am instead running into other errors.

2022-10-05 18:42 UTC, perrygreenfield commented
The problem with these tutorials is when relevant schemas are updated, so do the example files need to be. It's almost like there needs to be a script to reconstruct the example files without manual intervention.

2025-08-06 19:57 UTC, braingram commented
Closing in favor of the CI merged in https://github.com/asdf-format/tutorials/pull/20

2025-08-06 19:57 UTC, closed without merging